---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cybera_consul::default]
    attributes:
  - name: server
    run_list:
      - recipe[cybera_consul::server]
  - name: dns
    run_list:
      - recipe[cybera_consul::dns]
  - name: ui
    run_list:
      - recipe[cybera_consul::ui]
